// Code generated by protoc-gen-zig
///! package testproto.v1
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;

pub const METHOD = enum(i32) {
    METHOD_UNSPECIFIED = 0,
    METHOD_GET = 1,
    METHOD_POST = 2,
    METHOD_PUT = 3,
    METHOD_DELETE = 4,
    METHOD_OPTION = 5,
    _,
};

pub const Request = struct {
    method: METHOD = @enumFromInt(0),
    url: ManagedString = .Empty,
    body: ManagedString = .Empty,

    pub const _desc_table = .{
        .method = fd(1, .{ .Varint = .Simple }),
        .url = fd(2, .String),
        .body = fd(3, .Bytes),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const EncryptedPassword = struct {
    name: ManagedString = .Empty,
    encrypted: ManagedString = .Empty,

    pub const _desc_table = .{
        .name = fd(1, .String),
        .encrypted = fd(2, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
